name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: "3.0.2"

      - run: npm install
      - run: npm test
